### ISSUE TITLE
Single system user for all the node types

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#101]
Currently each node uses its own user to run processes. Bootnode uses `bootnode` and moc uses `moc` user. Each user has its own keyfile. There is superuser root.

Login in as root is considered as bad security practice. Deployment playbooks should run as ordinary user with `sudo` privileges.  No `root` account configuration should be necessary.

I see no value for having different users on different hosts. The proposal is to have the same user running all the processes.

Playbooks put public key for the operator to the remote host so they can SSH as a `poa` user with their private key.

**Comment by ajkagy** [comment]
Hey Aleksey, I noticed something weird last night and wanted to see if this was related, but didn't want to open a new issue if it wasn't.

I noticed in the main site.yml the default user is ubuntu, but during the SSH key copy from the local to the remote it's a hard coded root user so it's copying the keys to /home/root/.ssh/authorized_keys instead of the intended /home/ubuntu/.ssh/authorized_keys therefore when ansible tries to login to the remote with ubuntu it never verifies the keys since they reside in root. Is this the intended functionality?

path: deployment-playbooks/roles/preconf/tasks/main.yml

<code>
- name: Add ssh keys for root
  authorized_key: user=root key={{ item }} state=present exclusive=yes
  with_items: "{{ ssh_root }}"</code>

**Comment by lexsys27** [comment]
Hi @ajkagy ,

if ansible is running this task it has connected to the remote host somehow :)

`ansible.cfg` [states][1] that ansible user is `root`. That means before you start provisioning you should enable `root` on the host and put Ansible public key there. It is not great from security standpoint.

The task you are referecing adds keys for the human operator to login as `root`.

To login as `ubuntu` please use `usermanager` role. It will grab `files/ssh_ubuntu.pub` and put it into `~/.ssh/authorized_keys` on the host.

[1]: https://github.com/poanetwork/deployment-playbooks/blob/master/ansible.cfg#L11

**Comment by ajkagy** [comment]
Aleksey, sorry I should have been clearer. For the initial ssh connection I basically had to add the user/pass as params in my hosts file as a work around.

This all makes sense. Thanks!

**Comment by ArseniiPetrovich** [comment]
For backward compatibility and effortless fail check it will be better to keep roles separated.
As far as #110 were created that issue should be closed.
